enum SPORT_PHYSICAL_SKILL_CATEGORIES {
    RANGE = "RANGE",
    ACCURACY = "ACCURACY"
}

enum SPORT_PHYSICAL_MEASURE_FORMAT {
    RANGE = "RANGE",
    NUMBER = "NUMBER",
    METERS = "METERS",
    CENTIMETERS = "CENTIMETERS",
    FEETS = "FEETS",
    KILOMETERS = "KILOMETERS",
    MILES = "MILES",
    KM_PER_HOUR = "KM_PER_HOUR",
    MILES_PER_HOUR = "MILES_PER_HOUR",
}

type SportPhysicalSkill = {
    value?: number
    measureFormat?: SPORT_PHYSICAL_MEASURE_FORMAT
    category: SPORT_PHYSICAL_SKILL_CATEGORIES
}

export {
    SPORT_PHYSICAL_SKILL_CATEGORIES,
    SPORT_PHYSICAL_MEASURE_FORMAT,
    SportPhysicalSkill
}